# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.0

commands:
  get_npm:
    description: "Install nodejs"
    steps:
      - run:
          name: Install nodejs
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

  get_meta:
    description: "Install meta"
    steps:
      - run:
          name: install meta
          command: |
            sudo npm install -g meta

  clone_sub_repos:
    description: "Clone sub-repositories"
    steps:
      - run:
          name: "Clone with meta"
          command: |
            meta git update

  test:
    description: "Run test on all sub-repos"
    steps:
      - run:
          name: "Run tests"
          command: |
            source scripts/setup_env
            meta exec bundle
            meta exec "bundle exec rake"

jobs:
  "ruby-2.6":
    docker:
       - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - get_npm
      - get_meta
      - clone_sub_repos
      - test

  "ruby-2.5":
    docker:
       - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - get_npm
      - get_meta
      - clone_sub_repos
      - test

  "ruby-2.4":
    docker:
       - image: circleci/ruby:2.4
    working_directory: ~/repo
    steps:
      - checkout
      - get_npm
      - get_meta
      - clone_sub_repos
      - test

  "ruby-2.3":
    docker:
       - image: circleci/ruby:2.3
    working_directory: ~/repo
    steps:
      - checkout
      - get_npm
      - get_meta
      - clone_sub_repos
      - test


workflows:
  version: 2
  build:
    jobs:
      # Keep lowest ruby-* version in sync with cucumber.gemspec & .rubocop.yml
      - "ruby-2.6"
      - "ruby-2.5"
      - "ruby-2.4"
      - "ruby-2.3"
