# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

commands:
  install_npm:
    description: "Install nodejs"
    steps:
      - run:
          name: Install nodejs
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

  install_meta:
    description: "Install meta"
    steps:
      - run:
          name: install meta
          command: |
            npm install --no-save meta

  clone_sub_repos:
    description: "Clone sub-repositories"
    steps:
      - run:
          name: "Clone with meta"
          command: |
            node_modules/meta/bin/meta git update

  use_same_branch:
    description: "Use same branch on all sub-repos"
    steps:
      - run:
          name: "use correct branch on all sub-repos"
          command:
            node_modules/meta/bin/meta git checkout $CIRCLE_BRANCH
            node_modules/meta/bin/meta git pull

  test:
    description: "Run test on all sub-repos"
    steps:
      - run:
          name: "Run tests"
          command: |
            source scripts/setup_env
            node_modules/meta/bin/meta exec bundle
            node_modules/meta/bin/meta exec "bundle exec rake"

jobs:
  ruby-27:
    docker:
       - image: circleci/ruby:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - install_npm
      - install_meta
      - clone_sub_repos
      - use_same_branch
      - test

  ruby-26:
    docker:
       - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - install_npm
      - install_meta
      - clone_sub_repos
      - use_same_branch
      - test

  ruby-25:
    docker:
       - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - install_npm
      - install_meta
      - clone_sub_repos
      - use_same_branch
      - test

workflows:
  version: 2
  build:
    jobs:
      # Keep lowest ruby-* version in sync with cucumber.gemspec & .rubocop.yml
      - ruby-25
      - ruby-26
      - ruby-27
