# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.0

jobs:
  "ruby-2.6":
    docker:
       - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install -g meta
            source scripts/setup_env
            meta exec bundle
      - run:
          name: Run tests on all sub-repos
          command: meta exec "bundle exec rake"
  "ruby-2.5":
    docker:
       - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install -g meta
            source scripts/setup_env
            meta exec bundle
      - run:
          name: Run tests on all sub-repos
          command: meta exec "bundle exec rake"

  "ruby-2.4":
    docker:
       - image: circleci/ruby:2.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install -g meta
            source scripts/setup_env
            meta exec bundle
      - run:
          name: Run tests on all sub-repos
          command: meta exec "bundle exec rake"

  "ruby-2.3":
    docker:
       - image: circleci/ruby:2.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install -g meta
            source scripts/setup_env
            meta exec bundle
      - run:
          name: Run tests on all sub-repos
          command: meta exec "bundle exec rake"


workflows:
  version: 2
  build:
    jobs:
      # Keep lowest ruby-* version in sync with cucumber.gemspec & .rubocop.yml
      - "ruby-2.6"
      - "ruby-2.5"
      - "ruby-2.4"
      - "ruby-2.3"
